spring:
    application.name: EnergyMonitor
    banner.location: static/banner.txt
    datasource:
     datasource:
         url: jdbc:h2:mem:energy-monitor
         driverClassName: org.h2.Driver
#         driver-class-name: org.h2.Driver
         username: ${DBUSER:admin}
         password: ${DBPASS:}
     h2:
         console:
             enabled: true
             path: /database
             settings.web-allow-others: true
    jpa:
#         database-platform: org.hibernate.dialect.H2Dialect
        open-in-view: false
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                format_sql: true

