spring:
    application.name: EnergyMonitor
    banner.location: static/banner.txt
    datasource:
        url: jdbc:postgresql://localhost:5432/energy-monitor
        driverClassName: org.postgresql.Driver
        username: ${DBUSER:user}
        password: ${DBPASS:123}
    # datasource:
    #     url: jdbc:h2:mem:energy-monitor
    #     driverClassName: org.h2.Driver
    #     username: ${DBUSER:admin}
    #     password: ${DBPASS:}
    # h2:
    #     console:
    #         enabled: true
    #         path: /database
    #         settings.web-allow-others: true
    jpa:
        # database-platform: org.hibernate.dialect.H2Dialect
        open-in-view: false
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

